export const CHANGE_SEARCH_DATA = 'CHANGE_SEARCH_DATA';

export const CHANGE_SCREEN = 'CHANGE_SCREEN';

export const CHANGE_RESULTS = 'CHANGE_RESULTS';

export const CHANGE_SELECTED_OUTBOUND_JOURNEY = 'CHANGE_SELECTED_OUTBOUND_JOURNEY';
export const CHANGE_SELECTED_OUTBOUND_TICKET = 'CHANGE_SELECTED_OUTBOUND_TICKET';
export const CHANGE_SELECTED_INBOUND_JOURNEY = 'CHANGE_SELECTED_INBOUND_JOURNEY';
export const CHANGE_SELECTED_INBOUND_TICKET = 'CHANGE_SELECTED_INBOUND_TICKET';
